### ISSUE TITLE
Minimum coverage

### ISSUE THREAD

**Issue by armintoepfer** [rvaser/spoa#10]
First up, great work!

Is there any chance you can add a minimum coverage requirement before calling a base? The idea behind that, if I have 10 reads with a large deletion and 2 with a partial deletion, I only want to call bases in the consensus with at least coverage of, e.g., 5.

Thank you!

**Comment by rvaser** [comment]
Hello,
I am not sure if I understand your request. You want to call consensus if each base has at least 5 coverage? Or you want only those bases with at least 5 coverage?

Thanks for kind words!

**Comment by rvaser** [comment]
@armintoepfer ?

**Comment by rvaser** [comment]
@armintoepfer, I am pinging you if you by any chance have not seen my reply.

**Comment by armintoepfer** [comment]
Oh sorry. I figured it out on my own.
