### ISSUE TITLE
parameter setting to print out POA

### ISSUE THREAD

**Issue by ksahlin** [rvaser/spoa#13]
Hi Robert,

Spoa seems like a great tool/library that were looking to use in our next project. Would it be possible for you to add a parameter setting (or add a setting to the `-r`) to print the POA graph? Regarding the format I maybe it could be an adjacency list or similar, with weights in each-edge tuple. 

I'm assuming all the information necessary is in the structure `graph = spoa::createGraph();` but I'm unfortunately not proficient in C/C++ and looking to call spoa from python.

**Comment by rvaser** [comment]
The sample data in test/ yields the following image:

![g](https://user-images.githubusercontent.com/6094359/51714677-4c2f4580-2036-11e9-8734-91a522c02f3b.png)

**Comment by ksahlin** [comment]
Great, thanks! 

Dot format should work great and is actually easy to import into python/networkx. The important thing is to have all the information present in the graph to the output.

**Comment by rvaser** [comment]
Could you please specify which information you want in node labels and which in edge labels? Current version has node_id and character for nodes, and weight for edges.

**Comment by ksahlin** [comment]
It would actually be helpful with your expertise on that question for what is needed. The goal is to investigate alternative ways to derive consensus sequences from this graph (not necessarily the ML path).

Regarding the two different edge types: as long as they are distinguishable it should suffice. It actually makes sense not to have arrows on the mismatches --  so thats preferred. I can easily implement my own parser for this format if it becomes complicated and doesn't follow standards.

Weights on edges and directionality (not for mismatches) is definitely crucial. However, is there any additional information used for construction of consensus? Things like weights on nodes comes to mind.

**Comment by ksahlin** [comment]
Oh, misread your post. It doesn't matter that mismatches are directed, Ill take that into account from my parser!

**Comment by rvaser** [comment]
No additional info is used in the heaviest path algorithm. I think the current format will suffice then. I'll push the update to master in the morning.

**Comment by ksahlin** [comment]
Excellent, thanks!

**Comment by rvaser** [comment]
I pushed an optional parameter `-d <file>` to master branch (`v1.1.4`). Let me know if you need anything else.

**Comment by rvaser** [comment]
When using phred qualities I wanted that both bases somehow contribute to the edge weight so I decided to use averages but left out the division/shift.

**Comment by ksahlin** [comment]
Ok that makes sense, and great to know it supports phred values in the graph.

I consider this feature request solved, but I will explore this over the coming weeks and let you know of there's something that comes up. 

Thanks a lot for your help!

**Comment by rvaser** [comment]
I guess you are missing a new line at the end of your file. I have updated the parser for this but didn't pull it here. Will fix it in a moment.

**Comment by rvaser** [comment]
Should be fixed in `1.1.5`. I enabled compressed input files as well.
