### ISSUE TITLE
SOVERSION is something else than version of the software

### ISSUE THREAD

**Issue by tillea** [rvaser/spoa#14]
Hi,
I have packaged spoa for Debian and intend to upgrade the package to your latest upstream version 1.1.5.  I realised that your are simply re-using the version of the software as soversion.  This is not how soversion should be dealt with.  It should only be bumped in case of an ABI change and if a new version does not change the ABI the soversion should stay the same.  While I realised that there is actually an ABI change (there are some symbols missing) I will simply stick to this to not derive from your code too much.  But in case you will release a new version of spoa without any ABI change (ABI changes should be restrictet to those that are *really* necessary anyway) I'd recommend to stick to soversion 1.1.5 and for the next ABI change I'd recommend soversion 2 (or something like this).
Kind regards, Andreas.

**Comment by rvaser** [comment]
Thank you for the clarification Andreas, will keep it mind next time!
