### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by zeeev** [rvaser/spoa#23]
Hi @rvaser,

Not sure what is wrong this command. Oddly, passing in the three fasta sequences separately it works.

Unrelated, is there a way to modify the dot output to condense uniq paths into a single node?

```
(base) [zkronenberg@mp0709-sge chr2_q37_1]$ ~/tools/spoa/build/bin/spoa -d test homSap_combined.fasta
Segmentation fault (core dumped)
```

[homSap_combined.fasta.zip](https://github.com/rvaser/spoa/files/3607452/homSap_combined.fasta.zip)

**Comment by rvaser** [comment]
Hi @zeeev,
your sequences are a bit too large for the current implementation which is limited to a 4GB space for all matrices (not sure if there was a reason for this restriction). Will see what I can do.

At this point, the dot output is the complete graph. I think adding a sparse option might be doable.

Sorry for the late reply.
Best regards,
Robert

**Comment by maickrau** [comment]
I'm also running into a segmentation fault from too large sequences. I'm running `spoa --algorithm 1 --result 0 seqs.fa > consensus.fa`
[seqs.fa.zip](https://github.com/rvaser/spoa/files/5471324/seqs.fa.zip)

**Comment by rvaser** [comment]
Hi Mikko,
please checkout branch `large_sequences_fix`, your example should be working (if you have enough RAM). If you have any similar input, please try it as well.

@zeeev, sorry for not resolving this issue sooner, got swamped with work and later forgot. If your machine does not have enough memory, an error message will be printed. Your sequences are quite large, but you should be able to run smaller samples now.

Best regards,
Robert

**Comment by zeeev** [comment]
Thanks @rvaser! No worries, I know how busy things can get.

**Comment by rvaser** [comment]
@maickrau, the fix is now live on master branch (and soon conda).

**Comment by maickrau** [comment]
Thanks! It works great now
