### ISSUE TITLE
Output MSA as FASTA

### ISSUE THREAD

**Issue by rvaser** [rvaser/spoa#30]

**Comment by nh13** [comment]
Any chance for a graph output like http://gfa-spec.github.io/GFA-spec/GFA1.html. I may have missed it.

**Comment by rvaser** [comment]
I have created a new issue #32

**Comment by rvaser** [comment]
Implemented in commit https://github.com/rvaser/spoa/commit/09db33737198e37396aca48fe3b07640dce71082.
