### ISSUE TITLE
Output graph as GFA

### ISSUE THREAD

**Issue by rvaser** [rvaser/spoa#32]

**Comment by ekg** [comment]
This would be great!

How is the graph represented internally? I'd like to wrap it in a handlegraph (https://github.com/vgteam/libhandlegraph) abstraction.

**Comment by rvaser** [comment]
Hi Erik,
you can check the implementation here: https://github.com/rvaser/spoa/blob/master/include/spoa/graph.hpp. I'll try to add the GFA output soon. Sorry for my delayed reply.

Best regards,
Robert
