### ISSUE TITLE
[bioparser::FastqParser] error: invalid file format!

### ISSUE THREAD

**Issue by ksahlin** [rvaser/spoa#34]
Hi @rvaser, 

I get
`
[bioparser::FastqParser] error: invalid file format!
`

when running 
```
spoa ~/tmp/stefan_isonclust/bugfix/fastq_file_not_working.fq -l 0 -r 0 -g -2
```
My version of spoa
```
(base)  kxs624$ spoa --version
v1.1.5
```

I have attached the file `fastq_file_not_working.fq` (but I renamed it .txt in order to upload it here)
[fastq_file_not_working.txt](https://github.com/rvaser/spoa/files/4605572/fastq_file_not_working.txt)

I tried to look in the file for any malformatting, but the file is automatically generated so doubt it. I note however that the accession names are pretty long. Any idea what it could be?

**Comment by rvaser** [comment]
Hi @ksahlin,
quality string of read `Seq30580_2b38d1a2-f553-46f7-b71a-e7d9125464faf26c462c-ab17-4ef9-a3ce-2a20178e11d2_runid=80c496c696dcab90b5e62ead76f73930f9f2c6bd_read=241_ch=137_start_time=2017-05-24T13` is longer than the sequence string (8533 vs 8524).

Best regards,
Robert

**Comment by ksahlin** [comment]
Oh okay, I guess I should also implement such initial checks within my software :) 

Excellent, thanks!
