### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by zhenzhenyang-psu** [rvaser/spoa#40]
hello there,
I had a make error with error msgs like below, any idea?

In file included from /public/home/yangzhzh/tools_zz/spoa/src/sisd_alignment_engine.hpp:14,
                 from /public/home/yangzhzh/tools_zz/spoa/src/alignment_engine.cpp:12:
/public/home/yangzhzh/tools_zz/spoa/include/spoa/alignment_engine.hpp:30: error: expected nested-name-specifier before 'Alignment'
/public/home/yangzhzh/tools_zz/spoa/include/spoa/alignment_engine.hpp:30: error: 'Alignment' has not been declared
/public/home/yangzhzh/tools_zz/spoa/include/spoa/alignment_engine.hpp:30: error: expected ';' before '=' token
/public/home/yangzhzh/tools_zz/spoa/include/spoa/alignment_engine.hpp:30: error: expected unqualified-id before '=' token
/public/home/yangzhzh/tools_zz/spoa/include/spoa/alignment_engine.hpp:50: error: 'Alignment' does not name a type
/public/home/yangzhzh/tools_zz/spoa/include/spoa/alignment_engine.hpp:53: error: 'Alignment' does not name a type
In file included from /public/home/yangzhzh/tools_zz/spoa/src/alignment_engine.cpp:12:
/public/home/yangzhzh/tools_zz/spoa/src/sisd_alignment_engine.hpp:30: error: expected ';' before 'override'
/public/home/yangzhzh/tools_zz/spoa/src/sisd_alignment_engine.hpp:32: error: 'Alignment' does not name a type
/public/home/yangzhzh/tools_zz/spoa/src/sisd_alignment_engine.hpp:47: error: 'Alignment' does not name a type
/public/home/yangzhzh/tools_zz/spoa/src/sisd_alignment_engine.hpp:50: error: 'Alignment' does not name a type
/public/home/yangzhzh/tools_zz/spoa/src/sisd_alignment_engine.hpp:53: error: 'Alignment' does not name a type
/public/home/yangzhzh/tools_zz/spoa/src/sisd_alignment_engine.hpp:60: error: expected ';' before 'noexcept'
In file included from /public/home/yangzhzh/tools_zz/spoa/src/alignment_engine.cpp:13:
/public/home/yangzhzh/tools_zz/spoa/src/simd_alignment_engine.hpp:43: error: expected ';' before 'override'
/public/home/yangzhzh/tools_zz/spoa/src/simd_alignment_engine.hpp:45: error: 'Alignment' does not name a type
/public/home/yangzhzh/tools_zz/spoa/src/simd_alignment_engine.hpp:61: error: expected constructor, destructor, or type conversion before 'linear'
/public/home/yangzhzh/tools_zz/spoa/src/simd_alignment_engine.hpp:65: error: expected constructor, destructor, or type conversion before 'affine'
/public/home/yangzhzh/tools_zz/spoa/src/simd_alignment_engine.hpp:69: error: expected constructor, destructor, or type conversion before 'convex'
/public/home/yangzhzh/tools_zz/spoa/src/simd_alignment_engine.hpp:78: error: expected initializer before 'noexcept'
/public/home/yangzhzh/tools_zz/spoa/src/alignment_engine.cpp: In function 'std::unique_ptr<spoa::AlignmentEngine, std::default_delete<spoa::AlignmentEngine> > spoa::createAlignmentEngine(spoa::AlignmentType, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t)':
/public/home/yangzhzh/tools_zz/spoa/src/alignment_engine.cpp:64: error: 'nullptr' was not declared in this scope
/public/home/yangzhzh/tools_zz/spoa/src/alignment_engine.cpp: At global scope:
/public/home/yangzhzh/tools_zz/spoa/src/alignment_engine.cpp:77: error: 'Alignment' does not name a type
make[2]: *** [CMakeFiles/spoa.dir/src/alignment_engine.cpp.o] Error 1
make[1]: *** [CMakeFiles/spoa.dir/all] Error 2
make: *** [all] Error 2

thanks a lot,
Zhenzhen

**Comment by rvaser** [comment]
Hi Zhenzhen,
your compiler is too old. Update it or install a newer one locally and run:
```bash
cmake -DCMAKE_C_COMPILER=<path_to_c_compiler> -DCMAKE_CXX_COMPILER=<path_to_c++_compiler> -DCMAKE_BUILD_TYPE=Release ..
```

Best regards,
Robert

**Comment by zhenzhenyang-psu** [comment]
Hi Robert,
thanks very much. I will try newer versions of g++.
Best,
zhenzhen

**Comment by zhenzhenyang-psu** [comment]
it is now working! thanks a lot:)
