### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by paoloczi** [rvaser/spoa#41]
A Shasta user (@zhenzhenyang-psu) is getting an "Illegal instruction" signal while running the assembly phase that uses the spoa library. The signal occurs immediately on starting that assembly phase. He is using Shasta 0.5.0, which links in Spoa 3.4.0. He is running on an old CentOS 6 system, and it is likely that the processors are missing some of the newer instruction sets. I suspect an error in the recently introduced cpu dispatching capability in Spoa.

I will ask @zhenzhenyang-psu to report the processor flags for his system, so we will know exactly what is the available instruction set.  

Depending on how quickly you are able to address this, we may have to downgrade Shasta back to Spoa 0.3.0, or perhaps just provide this user a temporary Shasta build done with Spoa 0.3.0.

For reference, the original Shasta issue is [here](https://github.com/chanzuckerberg/shasta/issues/157). The title is misleading because the issue was initially filed for a different problem.

**Comment by bagashe** [comment]
```
if(NOT spoa_generate_dispatch) # optimization flags defeat the purpose of dispatching
    if (spoa_optimize_for_portability)
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -msse4.1")
    elseif (spoa_optimize_for_native)
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=native")
    endif()
endif()
```
This is from spoa's cmakelists file. `spoa_optimize_for_portability` defaults to OFF and `spoa_optimize_for_native` defaults to ON. So when `spoa_generate_dispatch` is OFF, it builds the optimized version for native. 

**Summary**: This is my fault in how I install SPOA while building Shasta for old Kernels. I will fix that and re-open this issue if the problem persists.

**Comment by paoloczi** [comment]
Given this, I am closing this issue as the problem is on our side.
