### ISSUE TITLE
Using quality values from FastQ to generate consensus/graph

### ISSUE THREAD

**Issue by ms-gx** [rvaser/spoa#46]
I there any option to feed FastQ data to your algorithm in a way that it will use the quality information? From what I have seen I do not think so, but asking anyway, maybe you have something experimental?

Do you think this would make sense in general and if yes, would it be a big effort to implement this in your view (if not already existing)?

**Comment by rvaser** [comment]
Hi Michael,
FASTQ files are supported, and quality values will be used to generate the consensus sequence. If you have something different in mind, please elaborate.

Best regards,
Robert

**Comment by ms-gx** [comment]
Oh, then I got this wrong. Sorry, closing issue.
