### ISSUE TITLE
Spoa v4.0.0 doesn't work when input is FASTA

### ISSUE THREAD

**Issue by wwliao** [rvaser/spoa#49]
Hi Robert,

Recently I upgraded Spoa from v3.0.1 to v4.0.0 and everything works great when the input file in FASTQ format. However, when feeding a FASTA file, it shows:
```
$ spoa -r 2 test.fa
[spoa::Graph::AddAlignment] error: sequence and weights are of unequal size!
```

Thanks,
Wen-Wei

**Comment by rvaser** [comment]
Hi Wen-Wei,
it should be fixed now, thanks for pointing it out!

Best regards,
Robert

**Comment by wwliao** [comment]
It works now. Thanks a lot!
