### ISSUE TITLE
Issue when installing spoa

### ISSUE THREAD

**Issue by stanislasmorand** [rvaser/spoa#50]
Dear Robert Vaser and the SPOA team,
I tried to install spoa v4.0.0 but it failed at the cmake step.
Here is the log:
```
[22:34] morands@frrdcim20: spoa-4.0.0 $ module load cmake/3.18.4
[22:35] morands@frrdcim20: spoa-4.0.0 $ mkdir build
[22:35] morands@frrdcim20: spoa-4.0.0 $ cd build/
[22:35] morands@frrdcim20: build $ cmake ..
-- The CXX compiler identification is GNU 4.8.5
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:48 (add_subdirectory):
  The source directory

    /home/morands/LIBRARIES/spoa-4.0.0/vendor/cereal

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
See also "/home/morands/LIBRARIES/spoa-4.0.0/build/CMakeFiles/CMakeOutput.log".
```
Would you have any idea what went wrong during this step?
Thanks in advance for your precious help & time.
Stan

**Comment by rvaser** [comment]
Hi Stan,
try running `git submodule update --init --recursive`.

Best regards,
Robert

**Comment by stanislasmorand** [comment]
Thanks Robert for your fast reply and suggestion.
Here is the response to your command ;

```
[23:17] morands@frrdcim20: ~ $ git submodule update --init --recursive
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

```
Any other idea?
By the way, our Linux server is not connected to the internet. Don't know if that is important to help solving this issue.
Kindest regards,
Stan

**Comment by stanislasmorand** [comment]
Dear Robert,
I downloaded your latest release, the one from yesterday (the 43Mb file) and it went well (mkdir build, cd build, cmake .. and make). 
Sorry for the initial issue raised.
Cheers,
Stan
