### ISSUE TITLE
How to get both GFA and MSA as output?

### ISSUE THREAD

**Issue by AndreaGuarracino** [rvaser/spoa#51]
Hi @rvaser,

is it possible to obtain as output in a single run both the partial order graph (GFA) and the multiple sequence alignment (FASTA)?

**Comment by rvaser** [comment]
Hi Andrea,
at this point no. I'll figure out a way how to enable it, but in 2 weeks or so.

Best regards,
Robert

**Comment by rvaser** [comment]
I forgot about this issue, sorry. Would it be acceptable to print the GFA first, followed by an empty line, and then the FASTA (both to stdout)?

**Comment by AndreaGuarracino** [comment]
Hi Robert,

I think it would work because we users should just add a shell/convenient way to separate the two parts on the fly into two different files. Thank you!

**Comment by rvaser** [comment]
I enabled multiple `-r` options so you can mix and match different output formats as you like.

**Comment by AndreaGuarracino** [comment]
Nice, it is very general! I would suggest editing the documentation, because now, for example, `-r1 -r0` is very similar to `-r2`, but in the first case the consensus is without gaps (and its header is slightly different). However, it works well, thank you! Now I want #31. Push, push, push! :P
