### ISSUE TITLE
Install error: ‘Alignment’ has not been declared

### ISSUE THREAD

**Issue by shaohaojing** [rvaser/spoa#52]
Hi rvaser,

I try to install the tool and get these errors. Do you know how to fix it? 
Thanks,
Haojing

io2 09:37:11 ~/bin/spoa/build
$ make
[ 33%] Building CXX object CMakeFiles/spoa.dir/src/alignment_engine.cpp.o
In file included from /public/home/shaohaojing/bin/spoa/src/alignment_engine.cpp:3:
/public/home/shaohaojing/bin/spoa/include/spoa/alignment_engine.hpp:29: error: expected nested-name-specifier before ‘Alignment’
/public/home/shaohaojing/bin/spoa/include/spoa/alignment_engine.hpp:29: error: ‘Alignment’ has not been declared
/public/home/shaohaojing/bin/spoa/include/spoa/alignment_engine.hpp:29: error: expected ‘;’ before ‘=’ token
/public/home/shaohaojing/bin/spoa/include/spoa/alignment_engine.hpp:29: error: expected unqualified-id before ‘=’ token
/public/home/shaohaojing/bin/spoa/include/spoa/alignment_engine.hpp:61: error: ‘Alignment’ does not name a type
/public/home/shaohaojing/bin/spoa/include/spoa/alignment_engine.hpp:66: error: ‘Alignment’ does not name a type
In file included from /public/home/shaohaojing/bin/spoa/src/alignment_engine.cpp:10:
/public/home/shaohaojing/bin/spoa/src/sisd_alignment_engine.hpp:20: error: ‘spoa::SisdAlignmentEngine::SisdAlignmentEngine(spoa::SisdAlignmentEngine&&)’ cannot be defaulted
/public/home/shaohaojing/bin/spoa/src/sisd_alignment_engine.hpp:21: error: ‘spoa::SisdAlignmentEngine& spoa::SisdAlignmentEngine::operator=(spoa::SisdAlignmentEngine&&)’ cannot be defaulted
/public/home/shaohaojing/bin/spoa/src/sisd_alignment_engine.hpp:37: error: expected ‘;’ before ‘override’
/public/home/shaohaojing/bin/spoa/src/sisd_alignment_engine.hpp:39: error: ‘Alignment’ does not name a type
/public/home/shaohaojing/bin/spoa/src/sisd_alignment_engine.hpp:55: error: ‘Alignment’ does not name a type
/public/home/shaohaojing/bin/spoa/src/sisd_alignment_engine.hpp:60: error: ‘Alignment’ does not name a type
/public/home/shaohaojing/bin/spoa/src/sisd_alignment_engine.hpp:65: error: ‘Alignment’ does not name a type
/public/home/shaohaojing/bin/spoa/src/sisd_alignment_engine.hpp:77: error: expected ‘;’ before ‘noexcept’
In file included from /public/home/shaohaojing/bin/spoa/src/alignment_engine.cpp:11:
/public/home/shaohaojing/bin/spoa/src/simd_alignment_engine.hpp:34: error: ‘spoa::SimdAlignmentEngine<A>::SimdAlignmentEngine(spoa::SimdAlignmentEngine<A>&&)’ cannot be defaulted
/public/home/shaohaojing/bin/spoa/src/simd_alignment_engine.hpp:51: error: expected ‘;’ before ‘override’
/public/home/shaohaojing/bin/spoa/src/simd_alignment_engine.hpp:53: error: ‘Alignment’ does not name a type
/public/home/shaohaojing/bin/spoa/src/simd_alignment_engine.hpp:80: error: expected constructor, destructor, or type conversion before ‘Linear’
/public/home/shaohaojing/bin/spoa/src/simd_alignment_engine.hpp:86: error: expected constructor, destructor, or type conversion before ‘Affine’
/public/home/shaohaojing/bin/spoa/src/simd_alignment_engine.hpp:92: error: expected constructor, destructor, or type conversion before ‘Convex’
/public/home/shaohaojing/bin/spoa/src/simd_alignment_engine.hpp:108: error: expected initializer before ‘noexcept’
/public/home/shaohaojing/bin/spoa/src/alignment_engine.cpp:94: error: ‘Alignment’ does not name a type
/public/home/shaohaojing/bin/spoa/src/alignment_engine.cpp: In member function ‘int64_t spoa::AlignmentEngine::WorstCaseAlignmentScore(int64_t, int64_t) const’:
/public/home/shaohaojing/bin/spoa/src/alignment_engine.cpp:104: error: expected primary-expression before ‘[’ token
/public/home/shaohaojing/bin/spoa/src/alignment_engine.cpp:104: error: expected primary-expression before ‘]’ token
/public/home/shaohaojing/bin/spoa/src/alignment_engine.cpp:104: error: expected primary-expression before ‘len’
/public/home/shaohaojing/bin/spoa/src/alignment_engine.cpp:104: error: unable to deduce ‘auto’ from ‘<expression error>’
/public/home/shaohaojing/bin/spoa/src/alignment_engine.cpp:104: error: expected ‘,’ or ‘;’ before ‘{’ token
make[2]: *** [CMakeFiles/spoa.dir/src/alignment_engine.cpp.o] Error 1
make[1]: *** [CMakeFiles/spoa.dir/all] Error 2
make: *** [all] Error 2

**Comment by rvaser** [comment]
Hi Haojing,
please check your compiler version. If you have a newer one, please check whether it is picked up by cmake by running `make VERBOSE=1` (it will print the gcc/g++ path found).

Best regards,
Robert

**Comment by shaohaojing** [comment]
Hi Robert,
I fix the old one by updating cmake and gcc version. But I get another one. Do you have some ideas on it? 
Thanks,
Haojing

In file included from /public/home/shaohaojing/bin/spoa/vendor/bioparser/include/bioparser/fasta_parser.hpp:12:0,
                 from /public/home/shaohaojing/bin/spoa/src/main.cpp:5:
/public/home/shaohaojing/bin/spoa/vendor/bioparser/include/bioparser/parser.hpp:123:19: error: 'gzFile_s' was not declared in this scope
   std::unique_ptr<gzFile_s, int(*)(gzFile)> file_;
                   ^
/public/home/shaohaojing/bin/spoa/vendor/bioparser/include/bioparser/parser.hpp:123:43: error: template argument 1 is invalid
   std::unique_ptr<gzFile_s, int(*)(gzFile)> file_;
                                           ^

**Comment by rvaser** [comment]
Hi Haojing,
please update zlib.

Best regards,
Robert
