### ISSUE TITLE
Inconsistent output directory of libspoa.a

### ISSUE THREAD

**Issue by rlorigro** [rvaser/spoa#53]
Hi Robert,

I recently incorporated spoa into a project of mine using CMake and the ExternalProject functionality of CMake. I would like to make sure that the `lib/libspoa.a` is consistently located, so it can be used to initialize the CMake library:

https://github.com/vgteam/GetBlunted/blob/025bf7b7ea2b564495019129c4f22f1902beab68/CMakeLists.txt#L274

However, it appears that this directory is renamed `lib64` in certain contexts. The case where this happens for me is on CentOS 7-8.2003.0.el7.centos.x86_64 with the following CPU:
```
processor   : 0
vendor_id   : GenuineIntel
cpu family  : 6
model       : 46
model name  : Intel(R) Xeon(R) CPU           X7560  @ 2.27GHz
stepping    : 6
microcode   : 0xd
cpu MHz     : 2260.911
cache size  : 24576 KB
physical id : 0
siblings    : 16
core id     : 0
cpu cores   : 8
apicid      : 0
initial apicid  : 0
fpu     : yes
fpu_exception   : yes
cpuid level : 11
wp      : yes
flags       : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 sse4_2 x2apic popcnt lahf_lm ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid dtherm ida spec_ctrl intel_stibp flush_l1d
bogomips    : 4521.82
clflush size    : 64
cache_alignment : 64
address sizes   : 44 bits physical, 48 bits virtual
```

It does not happen on MacOS (unknown CPU) or on ubuntu 18.04 with the following CPU:
```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 158
model name	: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
stepping	: 9
microcode	: 0xde
cpu MHz		: 800.007
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit srbds
bogomips	: 8400.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6

```

Is there any way to predict when `lib` will be renamed to `lib64` ?

**Comment by rvaser** [comment]
Hi Ryan,
I have not encountered this type of problem yet. If you just compile spoa (make), the library should be in ${PROJECT_BINARY_DIR}/lib. On the other hand, if you install it to your machine (make install), it should be in ${CMAKE_INSTALL_LIBDIR}. Can you try and use this variables?

Best regards,
Robert

**Comment by rlorigro** [comment]
From a previous discussion, I decided to use this command:

![-DCMAKE_INSTALL_PREFIX=${CMAKE_SOURCE_DIR}/external/spoa/](https://github.com/vgteam/GetBlunted/blob/025bf7b7ea2b564495019129c4f22f1902beab68/CMakeLists.txt#L262)

And later it calls `make install`, which should send it to a directory in the top level of the repo: `external/spoa/` if i understand correctly.

I think this may be a case of CentOS doing its own thing, so I may just write a conditional statement to check for CentOS. I found some discussion about library naming conventions:

https://unix.stackexchange.com/questions/74646/difference-between-lib-lib32-lib64-libx32-and-libexec

I'll post the results here

**Comment by rlorigro** [comment]
Ah actually your solution seems better, I will test it on CentOS when i get the chance, thanks

Looks like this now:
```
        CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${CMAKE_SOURCE_DIR}/external/spoa/ -DCMAKE_INSTALL_LIBDIR=${CMAKE_SOURCE_DIR}/external/spoa/lib
```
