### ISSUE TITLE
Question: Obtain base qualities for the consensus sequence

### ISSUE THREAD

**Issue by nh13** [rvaser/spoa#6]
I was wondering if @rvaser had any thoughts on how to obtain a base quality value for each base in the returned consensus sequence.  I was thinking it could be one of two things, but there surely are more:

1. In the simplest form, the consensus base quality is the probability of the consensus base being wrong given only the non-N input bases that cover/overlap/align-to that consensus base.  The probability of error for each input base could either be a fixed value (FASTA) or the input base quality (FASTQ).

2. In a more complicated form, the consensus base quality could be produced using [base alignment quality (BAQ)](https://www.ncbi.nlm.nih.gov/pubmed/21320865).  This captures both the probability of the base being wrong, as well as the base being misaligned.

My intended use case for spoa and the consensus call is in DNA sequencing, where we know that a set of sequencing reads all observe (originate from) the same source molecule, using molecular tagging (i.e. unique molecular identifiers or molecular barcodes).  In this case, all the sequencing reads _should_ be the same, but due various errors in the sample and library preparation, as well as the act of sequencing, we get random and systematic errors.  The former are what consensus calling could squash (ex. https://github.com/mikessh/mageri).  I am working on incoporating MSA into (see these development branches in [callerpp](https://github.com/nh13/callerpp/pull/4) and [fgbio](https://github.com/fulcrumgenomics/fgbio/pull/373).  I'd be happy to discuss further over email if that works.

**Comment by rvaser** [comment]
Hello,
I have been playing with quality calculation on branch `feature_variants` where I calculate the quality of each base by summing the number of identical base that cover it, divided by all other bases plus deletions (only those deletions that are not on sequence ends). Check it out here https://github.com/rvaser/spoa/blob/feature_variants/src/graph.cpp#L487-L518. If you think that would work for your use case, I can implemented into current version. Feel free to email me.

Best regards,
Robert

**Comment by rvaser** [comment]
Now that base summary feature is implemented, do you need a special function to calculate qualities?

**Comment by nh13** [comment]
It would be a nice to have, but I think proble of how to do the calculation is application specific, so ideally there’d be a way to hook in a custom base quality calculation. For example, we could model simple error from the sequencer, both random and systematic, or even model upstream errors introduced in PCR amplification or via oxidation/deamination but there’s no clear “one model” so having access to the matrix is a really good start. It may end up being that how we generate the consensus (I.e. find the optimal path in the graph) also becomes application specific. I don’t have a well formed conclusion as of yet. Let me think about this more.

**Comment by rvaser** [comment]
@nh13, there was an infinite loop bug in base summaries which I fixed in the latest release `v1.1.2` (some indels were added to the sum by mistake as well and are fixed now). Just letting you know.

**Comment by nh13** [comment]
@rvaser thanks for keeping me in the loop!
