### ISSUE TITLE
Potential Meson addition

### ISSUE THREAD

**Issue by SoapZA** [rvaser/spoa#8]
Hi @rvaser 
Meson is a new build system that aims to improve a lot on the imperfections of CMake, like a nicer syntax, being non-turing complete, being faster and allowing trivial composability. One of the big drawbacks of CMake is that it was never designed to be composable, and as such all ways of bundling it are ultimately painful and break in idiosyncratic ways. Would you be open to me contributing a Meson PR? You can always just call a "best effort thing" and all problems with it should be dealt by me. Many projects are switching to Meson now, such as GNOME, the complete X.org stack and many others, hence this is not just a niche sideproject of some random guy.

**Comment by rvaser** [comment]
Hello @SoapZA,
I have heard of Meson before and am looking forward for your PR. When I get the time, I might add it to other submodules for easier integration. Will it be troublesome to include googletest as it does not provide a Meson build?

**Comment by rvaser** [comment]
:finnadie:
